/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateGiftingRouteImport } from './routes/corporate-gifting'
import { Route as DesignManufacturingRouteImport } from './routes/design-manufacturing'
import { Route as EmeraldsRouteImport } from './routes/emeralds'
import { Route as FashionHardwareRouteImport } from './routes/fashion-hardware'
import { Route as GemstonesRouteImport } from './routes/gemstones'
import { Route as JewelleryRouteImport } from './routes/jewellery'
import { Route as RubyRouteImport } from './routes/ruby'
import { Route as SapphiresRouteImport } from './routes/sapphires'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateGiftingRoute = CorporateGiftingRouteImport.update({
  id: '/corporate-gifting',
  path: '/corporate-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignManufacturingRoute = DesignManufacturingRouteImport.update({
  id: '/design-manufacturing',
  path: '/design-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmeraldsRoute = EmeraldsRouteImport.update({
  id: '/emeralds',
  path: '/emeralds',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionHardwareRoute = FashionHardwareRouteImport.update({
  id: '/fashion-hardware',
  path: '/fashion-hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const GemstonesRoute = GemstonesRouteImport.update({
  id: '/gemstones',
  path: '/gemstones',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRoute = JewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const RubyRoute = RubyRouteImport.update({
  id: '/ruby',
  path: '/ruby',
  getParentRoute: () => rootRouteImport,
} as any)
const SapphiresRoute = SapphiresRouteImport.update({
  id: '/sapphires',
  path: '/sapphires',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/design-manufacturing': typeof DesignManufacturingRoute
  '/emeralds': typeof EmeraldsRoute
  '/fashion-hardware': typeof FashionHardwareRoute
  '/gemstones': typeof GemstonesRoute
  '/jewellery': typeof JewelleryRoute
  '/ruby': typeof RubyRoute
  '/sapphires': typeof SapphiresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/design-manufacturing': typeof DesignManufacturingRoute
  '/emeralds': typeof EmeraldsRoute
  '/fashion-hardware': typeof FashionHardwareRoute
  '/gemstones': typeof GemstonesRoute
  '/jewellery': typeof JewelleryRoute
  '/ruby': typeof RubyRoute
  '/sapphires': typeof SapphiresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/design-manufacturing': typeof DesignManufacturingRoute
  '/emeralds': typeof EmeraldsRoute
  '/fashion-hardware': typeof FashionHardwareRoute
  '/gemstones': typeof GemstonesRoute
  '/jewellery': typeof JewelleryRoute
  '/ruby': typeof RubyRoute
  '/sapphires': typeof SapphiresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/corporate-gifting'
    | '/design-manufacturing'
    | '/emeralds'
    | '/fashion-hardware'
    | '/gemstones'
    | '/jewellery'
    | '/ruby'
    | '/sapphires'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/corporate-gifting'
    | '/design-manufacturing'
    | '/emeralds'
    | '/fashion-hardware'
    | '/gemstones'
    | '/jewellery'
    | '/ruby'
    | '/sapphires'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/corporate-gifting'
    | '/design-manufacturing'
    | '/emeralds'
    | '/fashion-hardware'
    | '/gemstones'
    | '/jewellery'
    | '/ruby'
    | '/sapphires'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  CorporateGiftingRoute: typeof CorporateGiftingRoute
  DesignManufacturingRoute: typeof DesignManufacturingRoute
  EmeraldsRoute: typeof EmeraldsRoute
  FashionHardwareRoute: typeof FashionHardwareRoute
  GemstonesRoute: typeof GemstonesRoute
  JewelleryRoute: typeof JewelleryRoute
  RubyRoute: typeof RubyRoute
  SapphiresRoute: typeof SapphiresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-gifting': {
      id: '/corporate-gifting'
      path: '/corporate-gifting'
      fullPath: '/corporate-gifting'
      preLoaderRoute: typeof CorporateGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-manufacturing': {
      id: '/design-manufacturing'
      path: '/design-manufacturing'
      fullPath: '/design-manufacturing'
      preLoaderRoute: typeof DesignManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emeralds': {
      id: '/emeralds'
      path: '/emeralds'
      fullPath: '/emeralds'
      preLoaderRoute: typeof EmeraldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion-hardware': {
      id: '/fashion-hardware'
      path: '/fashion-hardware'
      fullPath: '/fashion-hardware'
      preLoaderRoute: typeof FashionHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemstones': {
      id: '/gemstones'
      path: '/gemstones'
      fullPath: '/gemstones'
      preLoaderRoute: typeof GemstonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery': {
      id: '/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof JewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruby': {
      id: '/ruby'
      path: '/ruby'
      fullPath: '/ruby'
      preLoaderRoute: typeof RubyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sapphires': {
      id: '/sapphires'
      path: '/sapphires'
      fullPath: '/sapphires'
      preLoaderRoute: typeof SapphiresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  CorporateGiftingRoute: CorporateGiftingRoute,
  DesignManufacturingRoute: DesignManufacturingRoute,
  EmeraldsRoute: EmeraldsRoute,
  FashionHardwareRoute: FashionHardwareRoute,
  GemstonesRoute: GemstonesRoute,
  JewelleryRoute: JewelleryRoute,
  RubyRoute: RubyRoute,
  SapphiresRoute: SapphiresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
